package com.github.morulay.shiro.aad.spring.boot.autoconfigure;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.validation.constraints.NotBlank;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.validation.annotation.Validated;

/** Configuration properties for Shiro integration with Azure AD */
@Validated
@ConfigurationProperties(prefix = "shiro.aad")
public class ShiroAadProperties {

  /** Whether to enable Azure AD integration */
  private boolean enabled = true;

  /** Name of the tenant */
  @NotBlank private String tenant;

  /** Tenant ID of the tenant */
  @NotBlank private String tenantId;

  /**
   * Microsoft authority instance base URL. Default value is {@code
   * https://login.microsoftonline.com}
   */
  private String authority = "https://login.microsoftonline.com";

  /**
   * Unique application (client) ID assigned to your application by Azure AD when the application
   * was registered
   */
  @NotBlank private String clientId;

  /** Secret (password) provided by the application registration portal */
  private String clientSecret;

  /**
   * URI where the identity provider will send the security tokens back to. Default value is the
   * application root
   */
  private String redirectUri = "/";

  /**
   * URI that the user is redirected to after successfully signing out. If not provided, the user is
   * shown a generic message that's generated by the Microsoft identity platform endpoint
   */
  private String postLogoutUri;

  /** Name of authorization realm. Default value is {@code Azure Active Directory} */
  private String realmName = "Azure Active Directory";

  /**
   * {@link Set} of MIME types for which the filter will return {@code 401 Unauthorized} instead to
   * redirect using {@code 302 Found} to authorization endpoint of identity provider. Default is
   * {@code application/json}
   */
  private Set<String> noRedirectMimes = new HashSet<>(Arrays.asList("application/json"));

  /**
   * {@link Map} of path to filters to allow filter chain configuration
   *
   * <pre>
   * shiro:
   *   aad:
   *     filter-chain-defs:
   *       "[/static/**]": anon
   * </pre>
   */
  private Map<String, String> filterChainDefs;

  public boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(boolean enabled) {
    this.enabled = enabled;
  }

  public String getTenant() {
    return tenant;
  }

  public void setTenant(String tenant) {
    this.tenant = tenant;
  }

  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public String getAuthority() {
    return authority;
  }

  public void setAuthority(String authority) {
    this.authority = authority;
  }

  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public String getRedirectUri() {
    return redirectUri;
  }

  public void setRedirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
  }

  public String getClientSecret() {
    return clientSecret;
  }

  public void setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
  }

  public String getPostLogoutUri() {
    return postLogoutUri;
  }

  public void setPostLogoutUri(String postLogoutUri) {
    this.postLogoutUri = postLogoutUri;
  }

  public String getRealmName() {
    return realmName;
  }

  public void setRealmName(String realmName) {
    this.realmName = realmName;
  }

  public Set<String> getNoRedirectMimes() {
    return noRedirectMimes;
  }

  public void setNoRedirectMimes(Set<String> noRedirectMimes) {
    this.noRedirectMimes = noRedirectMimes;
  }

  public Map<String, String> getFilterChainDefs() {
    return filterChainDefs;
  }

  public void setFilterChainDefs(Map<String, String> filterChainDefs) {
    this.filterChainDefs = filterChainDefs;
  }
}
