package com.github.morulay.shiro.aad;

import static java.lang.String.format;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import org.apache.shiro.SecurityUtils;
import org.apache.shiro.session.SessionException;
import org.apache.shiro.subject.Subject;
import org.apache.shiro.web.filter.PathMatchingFilter;
import org.apache.shiro.web.util.WebUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * In addition to executing {@link Subject#logout()} makes <a
 * href="https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#send-a-sign-out-request">
 * sign-out from Microsoft Identity Platform</a> redirecting at the end to post logout URI if
 * provided.
 */
public class AadLogoutFilter extends PathMatchingFilter {

  private static final Logger log = LoggerFactory.getLogger(AadLogoutFilter.class);

  private String authority;
  private String tenant;
  private String postLogoutUri;

  /**
   * @param authority the Microsoft authority instance base URI, e.g. {@code
   *     https://login.microsoftonline.com}
   * @param tenant the name of the tenant
   * @param postLogoutUri the URI that the user is redirected to after successfully signing out. If
   *     not provided, the user is shown a generic message that's generated by the Microsoft
   *     identity platform endpoint. This URL must match one of the redirect URIs registered for
   *     your application in the application registration portal
   */
  public AadLogoutFilter(String authority, String tenant, String postLogoutUri) {
    this.authority = authority;
    this.tenant = tenant;
    this.postLogoutUri = postLogoutUri;
  }

  @Override
  protected boolean preHandle(ServletRequest request, ServletResponse response) throws IOException {
    Subject subject = SecurityUtils.getSubject();
    try {
      subject.logout();
    } catch (SessionException ise) {
      log.debug(
          "Encountered session exception during logout. This can generally safely be ignored.",
          ise);
    }

    issueRedirect(request, response);
    return false;
  }

  protected void issueRedirect(ServletRequest request, ServletResponse response)
      throws IOException {
    String redirectUri = format("%s/%s/oauth2/v2.0/logout", authority, tenant);
    if (postLogoutUri == null) {
      WebUtils.issueRedirect(request, response, redirectUri);
    }

    Map<String, String> params = new HashMap<>();
    params.put("post_logout_redirect_uri", postLogoutUri);
    WebUtils.issueRedirect(request, response, redirectUri, params);
  }
}
